# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "759281c88f1f37828d0217f6961da063"
name = "calculadora-cuotas"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
